import streamlit as st

# Wrap all the text inside st.markdown() using triple quotes (""")
st.markdown("""
# Terms and Conditions

**Last Updated:** August 2026

Welcome to Achala Digital Vaidya (accessible via `https://achala-digital-vaidya.streamlit.app/`), operated by Achala Enterprises. By using our application, you agree to comply with and be bound by the following terms and conditions.

**1. Educational Purpose Only (Not Medical Advice)**
Achala Digital Vaidya is an artificial intelligence-based educational tool designed to translate and simplify medical terminology, particularly focusing on orthopedic and joint care. 
* **No Doctor-Patient Relationship:** The use of this application does not create a doctor-patient relationship. 
* **Not a Diagnosis:** The generated PDFs and clinical translations are strictly for educational purposes and must not be used to diagnose, treat, cure, or prevent any disease.
* **Consult a Professional:** Always seek the advice of a qualified healthcare provider with any questions you may have regarding a medical condition or active prescription. Never disregard professional medical advice or delay in seeking it because of information generated by this application.

**2. Accuracy of Artificial Intelligence**
While we utilize advanced AI models to process and simplify your uploaded reports, AI systems are subject to limitations and may occasionally generate inaccurate, incomplete, or inappropriate outputs ("hallucinations"). Achala Enterprises does not guarantee the 100% accuracy of the translated reports. 

**3. User Responsibilities**
You are responsible for ensuring that the documents you upload belong to you or that you have explicit legal permission to process them. We highly recommend blurring or cropping out personally identifiable information (such as patient names, phone numbers, and addresses) before uploading images to the platform.

**4. Limitation of Liability**
To the maximum extent permitted by Indian law, Achala Enterprises and its founders, employees, or affiliates shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the application, or from actions taken based on the AI-generated reports.

**5. Modifications to the Service**
Achala Enterprises reserves the right to modify or discontinue, temporarily or permanently, the service (or any part thereof) with or without notice.
""")